### ISSUE TITLE
Expose keycloak service in your keyclock module

### ISSUE THREAD

**Issue by itzikntn** [ferrerojosh/nest-keycloak-connect#96] opened 2021-12-05 06:31 UTC
Hi ,

keycloak service has many methodes that we as users want to use , for example getUserInfo()...
currently when i import your module i cannot acssess the keycloak service (contrary from usage in nodejs key cloak connect )

please expose it :)

**Comment by ferrerojosh** [comment] 2021-12-07 06:51
Duplicate of #32

**Closed by ferrerojosh** 2021-12-07 06:51 UTC
Labels: question
