### ISSUE TITLE
keycloak-connect  is deprecated and will be removed in the future

### ISSUE THREAD

**Issue by davidsarkany** [ferrerojosh/nest-keycloak-connect#187] opened 2024-06-12 14:13 UTC
keycloak-connect is deprecated and will be removed in the future.
https://github.com/keycloak/keycloak-nodejs-connect?tab=readme-ov-file#keycloak-nodejs-adapter

**Comment by cre8** [comment] 2024-06-12 14:31
duplicate of #110

**Closed** 2024-06-14 05:54 UTC
